### ISSUE TITLE
Tracking test integration of python-extension

### ISSUE THREAD

**Issue by fire** [maiself/godot-python-extension#42]
I want to call a Python library with two bound dlls and make it an app. 

Is it possible to use Godot Python? https://github.com/V-Sekai/godot/tree/vsk-robust-skin-weights-transfer-4.3/modules/robust_skin_weight_transfer

- [ ] like putting things into the correct location
- [ ] work on macOS
- [ ] work on Windows, Mac and Linux

This issue tracks my attempts to use Godot Python to work on robust weight transfer.
